version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
                
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  build:
    commands:
      - echo Starting build `date`
      - chmod +rx -R *
      - ./gradlew clean build -x test -i
      - ./gradlew fubar
      - chmod +rx -R *
      #- ls -la build/libs/oereb-web-service-0.0.1-SNAPSHOT.jar      
      - ls -la build/libs/     
      - ls -la build/
      - ls -la
      - pwd    
      - docker build -t sogis/oereb-web-service:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push sogis/oereb-web-service:latest
      - echo Deleting Dockerfile
      - rm Dockerfile
artifacts:
  files:
    - '**/*'
